title: '&9&l⚔'  # Текст титула
subtitle: '&6⚔ &f&lВы убили &f&l{victim} &6⚔'  # Текст субтитула
displayTime: 5  # Время отображения сообщения в секундах
killSound: ENTITY_PLAYER_LEVELUP  # Название звука

particles:
  enabled: true  # Включение/выключение партиклов
  type: CRIT_MAGIC  # Тип партиклов (например, CRIT_MAGIC, FLAME и т.д.)
  count: 20  # Количество партиклов
# Плейсхолдеры config.yml =>
# "{killer}", Ник убийцы.
# "{victim}", Ник жертвы.
